version: "3.9"

services:
  postgres:
    image: postgres:17-alpine
    container_name: civisense-db

    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: civisense

    ports:
      - "5432:5432"
